<!-- Message de notification -->

<!-- Code HTML à écrire -->


<!-- Liste des aliments -->
<table class="generic-table meal-list">
    <caption>Carte du restaurant</caption>
    <tbody>
        <!-- Code HTML à écrire -->
        <?php foreach($ttt as $meal): ?>

        	<tr>
        		<td>
        			<img src="<?= $wwwUrl; ?>/images/meals/<?= $meal['Photo']; ?>">
        		</td>
        		<td>
        			<?= $meal['Name']; ?>
        		</td>
        		<td>
        			<?= $meal['Description']; ?>
        		</td>
        		<td>
        			<?= $meal['SalePrice']; ?>€ 
        		</td>
        		<td>
        			<a href="<?= $requestUrl;?>/orders?id=<?= $meal['Id'];?> " class="button button-primary">Order</a>
        		</td>
        	</tr>
        <?php endforeach; ?>
    </tbody>
</table>

