<fieldset >
	<legend>Sign Up</legend>
	<form action="<?= $requestUrl; ?>/inscription" method="post" class="insc">
		<input type="text" name="firstname" placeholder="Firstname">
		<input type="text" name="lastname" placeholder="Lastname">
		<input type="email" name="email" placeholder="Email">
		<textarea cols="30" rows="5" name="address" placeholder="Address"></textarea>
		<input type="password" name="password" placeholder="Password">
		<input type="submit" value="Inscription" class="button button-primary">
    </form>
</fieldset> 